#!/usr/bin/env php
<?php

declare(strict_types=1);

use Dom\Element;
use Dom\HTMLDocument;
use Dom\Node;

const TEXT_NODE = 3;

/**
 * Generate localized static HTML pages from JSON translation catalogs.
 *
 * Usage:
 *   php tools/translate.php       # Generate every translations/*.json catalog
 *   php tools/translate.php es    # Generate only translations/es.json
 */

$projectRoot = dirname(__DIR__);
$catalogs = catalogPaths($projectRoot, array_slice($argv, 1));

foreach ($catalogs as $catalogPath) {
    generateCatalog($projectRoot, $catalogPath);
}

/** @return list<string> */
function catalogPaths(string $projectRoot, array $locales): array
{
    if ($locales !== []) {
        $paths = [];
        foreach ($locales as $locale) {
            if (!preg_match('/^[a-z]{2,3}(?:-[A-Z]{2})?$/', $locale)) {
                fail("Invalid locale '{$locale}'.");
            }
            $paths[] = "{$projectRoot}/translations/{$locale}.json";
        }
        return $paths;
    }

    $paths = glob("{$projectRoot}/translations/*.json");
    if ($paths === false || $paths === []) {
        fail('No translation catalogs found in translations/.');
    }

    sort($paths);
    return array_values($paths);
}

function generateCatalog(string $projectRoot, string $catalogPath): void
{
    if (!is_file($catalogPath)) {
        fail("Translation catalog not found: {$catalogPath}");
    }

    try {
        $catalog = json_decode(
            file_get_contents($catalogPath) ?: '',
            true,
            flags: JSON_THROW_ON_ERROR,
        );
    } catch (JsonException $error) {
        fail("Invalid JSON in {$catalogPath}: {$error->getMessage()}");
    }

    $locale = requiredString($catalog, 'locale', $catalogPath);
    $direction = requiredString($catalog, 'direction', $catalogPath);
    if (!in_array($direction, ['ltr', 'rtl'], true)) {
        fail("Catalog {$catalogPath} has invalid direction '{$direction}'.");
    }

    $pages = $catalog['pages'] ?? null;
    if (!is_array($pages) || $pages === []) {
        fail("Catalog {$catalogPath} must contain at least one page.");
    }

    foreach ($pages as $pageNumber => $page) {
        if (!is_array($page)) {
            fail("Page {$pageNumber} in {$catalogPath} must be an object.");
        }

        $sourceRelative = requiredString($page, 'source', $catalogPath);
        $outputRelative = requiredString($page, 'output', $catalogPath);
        $sourcePath = projectPath($projectRoot, $sourceRelative);
        $outputPath = projectPath($projectRoot, $outputRelative);

        $expectedOutputPrefix = "public/{$locale}/";
        if (!str_starts_with($outputRelative, $expectedOutputPrefix)) {
            fail("Output '{$outputRelative}' must be inside {$expectedOutputPrefix}.");
        }
        if (!is_file($sourcePath)) {
            fail("Source HTML not found: {$sourceRelative}");
        }

        $html = file_get_contents($sourcePath);
        if ($html === false) {
            fail("Could not read source HTML: {$sourceRelative}");
        }

        $document = HTMLDocument::createFromString($html);
        $document->documentElement->setAttribute('lang', $locale);
        $document->documentElement->setAttribute('dir', $direction);

        $replacements = $page['replacements'] ?? null;
        if (!is_array($replacements) || $replacements === []) {
            fail("Page {$sourceRelative} has no replacements.");
        }

        foreach ($replacements as $replacementNumber => $replacement) {
            applyReplacement(
                $document,
                $replacement,
                "{$catalogPath}, page {$sourceRelative}, replacement {$replacementNumber}",
            );
        }

        $generated = $document->saveHtml();
        $generated = preg_replace(
            '/^<!DOCTYPE html>\s*/i',
            "<!DOCTYPE html>\n<!-- Generated by tools/translate.php from {$sourceRelative}; do not edit directly. -->\n",
            $generated,
            1,
        ) ?? $generated;

        $outputDirectory = dirname($outputPath);
        if (!is_dir($outputDirectory) && !mkdir($outputDirectory, 0775, true) && !is_dir($outputDirectory)) {
            fail("Could not create output directory: {$outputDirectory}");
        }

        $temporaryPath = tempnam($outputDirectory, '.translate-');
        if ($temporaryPath === false || file_put_contents($temporaryPath, $generated) === false) {
            fail("Could not write generated page: {$outputRelative}");
        }
        if (!chmod($temporaryPath, 0644)) {
            @unlink($temporaryPath);
            fail("Could not set permissions on generated page: {$outputRelative}");
        }
        if (!rename($temporaryPath, $outputPath)) {
            @unlink($temporaryPath);
            fail("Could not replace generated page: {$outputRelative}");
        }

        echo "Generated {$outputRelative} ({$locale}, ", count($replacements), " replacements)\n";
    }
}

function applyReplacement(HTMLDocument $document, mixed $replacement, string $context): void
{
    if (!is_array($replacement)) {
        fail("{$context} must be an object.");
    }

    $selector = requiredString($replacement, 'selector', $context);
    $source = requiredString($replacement, 'source', $context);
    $target = requiredString($replacement, 'target', $context);
    $elements = $document->querySelectorAll($selector);
    if (count($elements) !== 1) {
        fail("{$context}: selector '{$selector}' must match one element; found " . count($elements) . '.');
    }

    $element = $elements->item(0);
    if (!$element instanceof Element) {
        fail("{$context}: selector '{$selector}' did not match an HTML element.");
    }

    $attribute = $replacement['attribute'] ?? null;
    if ($attribute !== null) {
        if (!is_string($attribute) || $attribute === '') {
            fail("{$context}: attribute must be a non-empty string.");
        }
        $current = $element->getAttribute($attribute);
        if ($current !== $source) {
            fail("{$context}: expected {$attribute}='{$source}', found '{$current}'.");
        }
        $element->setAttribute($attribute, $target);
        return;
    }

    $matches = [];
    collectMatchingTextNodes($element, $source, $matches);
    if (count($matches) !== 1) {
        fail("{$context}: expected one text node containing '{$source}', found " . count($matches) . '.');
    }

    $node = $matches[0];
    $value = $node->nodeValue ?? '';
    $start = strpos($value, $source);
    if ($start === false) {
        fail("{$context}: internal text match error for '{$source}'.");
    }

    $node->nodeValue = substr($value, 0, $start)
        . $target
        . substr($value, $start + strlen($source));
}

/** @param list<Node> $matches */
function collectMatchingTextNodes(Node $node, string $source, array &$matches): void
{
    foreach ($node->childNodes as $child) {
        if ($child->nodeType === TEXT_NODE && trim($child->nodeValue ?? '') === $source) {
            $matches[] = $child;
            continue;
        }
        collectMatchingTextNodes($child, $source, $matches);
    }
}

function requiredString(array $data, string $key, string $context): string
{
    $value = $data[$key] ?? null;
    if (!is_string($value) || $value === '') {
        fail("{$context} requires a non-empty '{$key}' string.");
    }
    return $value;
}

function projectPath(string $projectRoot, string $relativePath): string
{
    if ($relativePath === '' || str_starts_with($relativePath, '/') || str_contains($relativePath, '..')) {
        fail("Unsafe project-relative path: '{$relativePath}'.");
    }
    return "{$projectRoot}/{$relativePath}";
}

function fail(string $message): never
{
    fwrite(STDERR, "Translation generation failed: {$message}\n");
    exit(1);
}
